name: Output Issue Event Details

on:
    issues:
        types: [opened, edited, closed]

jobs:
    output-event-details:
        runs-on: ubuntu-latest

        steps:
            - name: Output Issue Details
              run: |
                  echo "Issue Event Details:"
                  echo "Action: ${{ github.event.action }}"
                  echo "Issue Number: ${{ github.event.issue.number }}"
                  echo "Issue Title: ${{ github.event.issue.title }}"
                  echo "Issue Body: ${{ github.event.issue.body }}"
                  echo "Issue State: ${{ github.event.issue.state }}"
